### ISSUE TITLE
either TLS Client Certificate or x5bag must always be present in parboiled connection

### ISSUE THREAD

**Issue by mcr** [anima-wg/constrained-voucher#128]
The kid hash isn't useful unless the MASA already has the Registrar's full public key.

~~~~
2) The kid contains what I think is the hash of public key, as clearly
   indicated in section 8.3, where the example says:

      h'A101382E',        # { "alg": EC256K1 }
       {
         "kid" : h'7890....1234'  # hash256(public key)
       },

(no wonder Peter used EC256K1!)

The problem that I have is that I don't have the public key for his Registrar.
It wasn't included in an x5bag, nor as a TLS Client Side Certificate, so I
can't validate anything.  I'd have to have registered the Registrar a priori.

Pre-registration is a supported mechanism.  For this case, where everything
is that way, I return a 406.    I wonder if 401 or 403 might be better in
this case.... or do we perhaps need new returns.

I prefer to always be able to support TOFU MASA, even if that policy is
turned off, so I think that Registrars need to always provide their signing
key in x5bag.
If doing x5bag, it seems wasteful to then include kid.
~~~~

**Comment by petervanderstok** [comment]
Michael,

My registrar sinds over the registrar certificate that contains the public key during the tls handshake. That is how my masa checks the signature. Actually the registrar sends over two certificates: one certificate you want and second its signer certificate (CA). If not. I made a mistake during my tls tryouts.

Peter.

⁣Peter van der Stok
***@***.***

BlueMail voor Android downloaden ​

Op 14 jul. 2021 19:37, om 19:37, Michael Richardson ***@***.***> schreef:

**Comment by mcr** [comment]
> Michael, My registrar sinds over the registrar certificate that contains the public key during the tls handshake. 

So I should be seeing a TLS Client Certificate then?
I don't think that I am, but I'll check the logs again.

**Comment by petervanderstok** [comment]
Hi Michael,

With all the modifications I forgot to test with my own masa.
While iesting, I found that
I loaded the CA certificate and the registrar certificate in the wrong 
order, such that only the CA certificate arrives in the MASA.

Later today I will redo the test, once everything is checked here.

Peter
Michael Richardson schreef op 2021-07-14 21:40:

>> Michael, My registrar sinds over the registrar certificate that 
>> contains the public key during the tls handshake.
> 
> So I should be seeing a TLS Client Certificate then?
> I don't think that I am, but I'll check the logs again.
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].


Links:
------
[1] 
https://github.com/anima-wg/constrained-voucher/issues/128#issuecomment-880158203
[2]

**Comment by EskoDijk** [comment]
My current view (correct me if I'm wrong) is that KID is optionally used by the Pledge Voucher Request, to make it easy for MASA to look up the correct public key for this Pledge in its own database. That way, the MASA can verify the Pledge's Voucher Request (i.e. prior-signed-voucher-request) without having to guess which key to use. As an alternative, the MASA could use the serialNumber for that so that it doesn't need/use the KID. In that case the Pledge wouldn't include KID I presume.
Note: the method to generate KID can vary, but the method is chosen by the Pledge Manufacturer hence also known to both Pledge and MASA.

Registrar has in general no purpose/need to include KID in its Registrar Voucher Request, because MASA doesn't do anything with it. The Registrar's signing certificate chain is fully or partly included in the Voucher Request i.e. in x5bag or in the CMS. In this case the method the Registrar will use to generate the KID is unknown to the MASA as there's no standard for KID as such. It's just an application-specific identifier.

I think the current issue deserves further discussion: why do we want to change the BRSKI specs by "removing" signing certs potentially from the Voucher Request, and replace this by certs harvested from the TLS connection?  In that case we need also to update BRSKI to allow this. And there should be a good reason to allow this additional flexibility as it complicates testing.
