### ISSUE TITLE
Review HB: explain why shorter URLs are useful

### ISSUE THREAD

**Issue by mcr** [anima-wg/constrained-voucher#135]
> (4) Discovery, URIs and Content Formats

    > Maybe an example of EST and BRSKI URIs helps the reader to see the
    > difference/optimization more easily? The terms URI and URL or both used in this
    > section. Are they used dedicatedly with their distinct meanings or are they
    > used interchangeably? Sometimes the term 'end point' is also spelled
    > 'end-point'. Why is there a fall-back (as MAY) to Content-Format 50 for the
    > shorter URLs?

**Comment by EskoDijk** [comment]
We write that Content-Format 50 (JSON) MAY be supported by the Registrar for /es /vs resources. This seems not the most useful feature, since a Pledge will be coded only with format 60 (CBOR) because that is the mandatory-supported one. You cannot count on format 50 to be there, so why would a Pledge developer even bother about trying to use it?

I guess the 'example of URIs' meant here is the full URI, short and long versions. (Otherwise Table 1 shows the savings in the URI already - but it does not show the savings related to the full URI length.)
