### ISSUE TITLE
the PVR -- "kid" could be pledge serial-number

### ISSUE THREAD

**Issue by mcr** [anima-wg/constrained-voucher#159]
If the pledge includes a kid, that's just to help the MASA (in the PVR sent Registrar->MASA) find the right key.

**Comment by EskoDijk** [comment]
From the COSE (RFC8152bis) document:

      The internal structure of 'kid'
      values is not defined and cannot be relied on by applications.
      Key identifier values are hints about which key to use.

That means in the PVR, the Pledge MAY include a 'kid' to help the MASA to identify the right key from its database. In a similar fashion, if the Registrar and MASA have some business relation the Registrar may get from the vendor a list of KIDs to do some additional checking. But this is optional; it might as well get a list of Pledge serial-numbers to do the same and a KID isn't needed then.

Above means we should not specify a format for 'kid', not any particular choice or hash scheme, etc. It can be any type of identifier that the vendor of the Pledge likes. A Registrar must be able to handle any format - treat as opaque byte string. Note that a Registrar doesn't have to do anything with 'kid', in principle - it can also just ignore the field.

**Comment by siethower** [comment]
Right, I have the same opinion not to restrict "kid" format/content in the PVR.  
As Pledge and MASA are related to one manufacturer, this can be handled.  
Means having the pledge-serial-number is a example for using the kid ...

**Comment by mcr** [comment]
The PVR kid can be anything that helps the MASA find the right key, agreed to privately by the MASA/Pledge.

The RVR kid can be anything that the business relationship requires, and Registrars' UI MUST be able to enter a kid value in binary (as a bstr) or in text (as a tstr) to included in the RVR.
The x5bag is also to be included as well, and the kid may identify something specific in the bag.

**Comment by siethower** [comment]
The usage of "kid" was motivated for OOB use cases where the signing certs is not carried inside PVR by "x5bag"/"x5c".
Our idea here was to use "kid" instead of "x5bag"/"x5c" header in the PVR to save space.  
"kid" than helps the MASA to find the used PVR signing certificate (IDevID EE), as not carried in "x5bag"/"x5c". 
MASA is than required to have a list/database with the corresponding IDevID EE certs.

**Comment by EskoDijk** [comment]
@siethower  Yes in case the MASA has its EE certs in a database, there's no need to send it in the PVR in an x5bag.  Similarly, the MASA could look up the EE cert in its database based on Pledge serial-number as the lookup key so 'kid' can be omitted entirely. In the diff for the PR here https://github.com/anima-wg/constrained-voucher/pull/169/files you can see the additional text I added for this.  The use case example of using 'kid' that I mention there is: "Pledge has multiple IDevID identities" such that the serial-number of the device isn't sufficient information to pick the single EE cert from the database.

Another example use case is what you mention I think, that the EE certs in the database are indexed on a key-id / hash instead of indexed on device serial-number.   Not sure we have to mention more use cases in the text, though.
