### ISSUE TITLE
verify examples match RFC8152 (raw signature)

### ISSUE THREAD

**Issue by mcr** [anima-wg/constrained-voucher#215]
Viktor has noticed that the examples in the document may be DER encoded rather than being a raw signature.

**Comment by EskoDijk** [comment]
Specifically, the signature in the example file pledge-to-regis.txt (Appendix C.3) is an ASN.1 DER encoded structure instead of the expected 64-byte raw signature. This needs to be fixed.

Furthermore, the example uses COSE algorithm ES256K (-47) which is marked as "not recommended" in the COSE algorithms registry (https://www.iana.org/assignments/cose/cose.xhtml)  Do we have any idea why this is not recommended?
Should we change our examples to use ES256 (-7) instead, which still has a "yes" in the recommended-column?

**Comment by mcr** [comment]
yes, we should use ES256 (-7), unless we have a reason to demonstrate flexibility, which I don't think we do.

**Comment by petervanderstok** [comment]
I used es256k due to conflict I had when passing from mbedtls to openssl. Don't ask   me how that could happen. Indeed, I use es256 now. Actually it is the certificate that determines the key choice.

⁣Peter van der Stok
***@***.***

BlueMail voor Android downloaden ​

Op 4 feb. 2022 19:03, om 19:03, Michael Richardson ***@***.***> schreef:
>yes, we should use ES256 (-7), unless we have a reason to demonstrate
>flexibility, which I don't think we do.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/anima-wg/constrained-voucher/issues/215#issuecomment-1030225072
>You are receiving this because you are subscribed to this thread.
>
>Message ID:
***@***.***>

**Comment by EskoDijk** [comment]
Ok, so we can agree to update to ES256 (-7). That's also compatible with the current key type of the certificates (I use the same key types to produce ES256 (-7) signed COSE objects.)

@petervanderstok Maybe you could update the COSE examples in Github now, or maybe you want to wait until I did a review of these examples in detail? (I did not yet do this.)  That will likely produce some more things to improve in the certificates and/or COSE examples.

**Comment by mcr** [comment]
Examples to be updated after interop.

**Comment by EskoDijk** [comment]
I'm now updating all examples (making a PR) as part of #237.

**Comment by EskoDijk** [comment]
Closed by #249
