### ISSUE TITLE
CoAP discovery - update 10.2.1 to match latest Join Proxy draft

### ISSUE THREAD

**Issue by mcr** [anima-wg/constrained-voucher#236]
Explain what port number and host number is default in the discovery replies.

**Comment by toerless** [comment]
Adding @cabo to help:

I would like to see an approved example reply from a CoRE server that includes two resource options:

a) a constrained BRSKI registrar (stateful) with an explicitly indicated IPv6 address and an explicitly indicted port number across which coaps is run.

b) a constrained BRSKI registrar (stateless) with an explicitly indicated IPv6 address and an explicitly indicated port number across which the stateless option is run. The stateless option uses a new shim 'jpy' header over UDP which contains a CBOR encoded header followed by CoAPs.

I want explicit IPv6 address in the resource reply because the CoRE server may be a directory server, so the registrar may be on a different IPv6 address.

I want explicit port numbers because i don't think we should have expect hard-coded UDP port numbers, not even for CoAPs.

**Comment by EskoDijk** [comment]
I can also try to add some text and "CoRE-proof" examples. The COAPS port used by a Registrar host would be typically the COAPS scheme default (5684) in which case the port number isn't indicated in the discovery response typically (i.e. it's "compressed" away as usual in URIs).   For the JPY-protocol port used by a Registrar host it must be indicated explicitly because the JPY protocol scheme doesn't have a port number allocated. It's up to the host software what to choose there.

**Comment by EskoDijk** [comment]
The task to be done for this item is to update Section 10.2.1 (CoAP discovery by Join Proxy) to match the latest draft-ietf-anima-constrained-join-proxy, and to refer to it also.

Desired examples:
* One example of JP that only supports stateless mode (the one mandatory mode), discovers, and gets the IP address and port of the Registrar-Proxy to use for CoAP based relaying. The port is a non-default one, purely selected by the Registrar(-Proxy) or its human operator.
* One example of JP that supports both modes, discovers, and gets the IP address and default coaps (DTLS) port (5684) of the Registrar, so no explicit port indicated.

@toerless @mcr feel free to comment here if you would like additional examples in.

**Comment by EskoDijk** [comment]
PR created at #243  , still to look at above comments and what new examples need to go in that aren't yet in draft-join-proxy.
