### ISSUE TITLE
coaps URIs for Registrar to MASA? 

### ISSUE THREAD

**Issue by csosto-pk** [anima-wg/constrained-voucher#41]
The /requestauditlog and /voucher-status are exchanged by the Registrar and MASA. The JRC will likely talk to MASA over a normal (not constrained) medium. I would not expect a MASA to live in the constrained world. 

Do we need /ra and /vs in Table 1?

**Comment by petervanderstok** [comment]
Hi Panos,

Just my guess,
I would say that you need it.
When a pledge contacts the Registrar it will use the abbreviations.
The registrar coe, continuing the conversation with MASA, will be
simpler when same short name can be used,
thus avoiding a mapping in the registrar.

Peter
Panos K. schreef op 2019-07-06de06:19:

> The /requestauditlog and /voucher-status are exchanged by the Registrar and MASA. The JRC will likely talk to MASA over a normal (not constrained) medium. I would not expect a MASA to live in the constrained world. 
> 
> Do we need /ra and /vs in Table 1? 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/anima-wg/constrained-voucher/issues/41?email_source=notifications&amp;email_token=ADCZGQIOYJRR6WNV22IA3WTP6AMNJA5CNFSM4H6SQX32YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G5UQ36A
[2]

**Comment by mcr** [comment]
Panos K. <notifications@github.com> wrote:
    > The /requestauditlog and /voucher-status are exchanged by the Registrar
    > and MASA. The JRC will likely talk to MASA over a normal (not
    > constrained) medium. I would not expect a MASA to live in the
    > constrained world.

Agreed. JRC to MASA communication is never constrained. It is HTTPS.

    > Do we need /ra and /vs in Table 1?

I agree that they should be removed.

**Comment by mcr** [comment]
peter van der stok <notifications@github.com> wrote:
    > Just my guess,
    > I would say that you need it.
    > When a pledge contacts the Registrar it will use the abbreviations.

But, the pledge does not do /requestauditlog.

    > The registrar coe, continuing the conversation with MASA, will be
    > simpler when same short name can be used,
    > thus avoiding a mapping in the registrar.

No, it's not any simpler, in fact, it's more complex because you can't use
the same subroutine.

Now, /voucher_status  (not, voucher-status, I've fixed that) is used from the
pledge to registrar.  Ditto enrollstatus, which inconsistently, does not have
an underscore.

Surprisingly to my implementor, these are never used from the registrar to MASA.
I include it in smarkaklink however.

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        |    IoT architect   [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by csosto-pk** [comment]
> peter van der stok <notifications@github.com> wrote: Just my guess, I would say that you need it. When a pledge contacts the Registrar it will use the abbreviations. But, the pledge does not do /requestauditlog. 
> [ ... ] 
> Now, /voucher_status (not, voucher-status, I've fixed that) is used from the pledge to registrar. 

Agreed. My bad. I should have only said /requestauditlog only. I think you don't need an abbreviated URI /ra in the draft for this because it is only JRC to MASA, it does not involve the pledge.

**Comment by csosto-pk** [comment]
Addressed in commit https://github.com/anima-wg/constrained-voucher/commit/613bd4ea901555c99d8760ff1d4fbfb66913d97e . 
Closing this issue now.
