### ISSUE TITLE
Payload in voucher_status example in A.2 to be updated

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/constrained-voucher#50]
In -07, payload decodes to:

{"version": "1", "Status": 1, "Reason": "Informative human readable message", "reason-context": "Additional information"}

which should be (per BRSKI-41):

{"version": "1", "status": false, "reason": "Informative human readable message", "reason-context": { "additional" : "JSON" } }

(status is changed to 'false' here, to encode an error status. If no error, there should be no 'reason' field as well. Also the additional-information is updated with a more clear example, but this is not super important to have. But it's more in line with BRSKI.

Also a success example could be added if needed:
{"version": "1", "status": true}

**Comment by EskoDijk** [comment]
See also #47 for more info

**Comment by EskoDijk** [comment]
See also https://github.com/anima-wg/anima-bootstrap/issues/144 for related issues in BRSKI. We should capture the outcome of this discussion in the constrained-voucher draft.

**Comment by mcr** [comment]
@petervanderstok , how did you create this example?

**Comment by petervanderstok** [comment]
By running my implementations , pledge, registrar, masa with the
certficates that are shown.

When changing the certificates, examples text needs to be modified by
hand due to 72 byte line limit.

Peter
Michael Richardson schreef op 2020-11-26 11:56:

> @petervanderstok [1] , how did you create this example? 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
 

Links:
------
[1] https://github.com/petervanderstok
[2]
https://github.com/anima-wg/constrained-voucher/issues/50#issuecomment-734228498
[3]
