### ISSUE TITLE
should the registrar/masa communication allow CoAP?

### ISSUE THREAD

**Issue by mcr** [anima-wg/constrained-voucher#58]
It seems convenient for some implementations to use CoAP from the Registrar to the MASA.

Some assumed that it could be either, but most prefer HTTPS.

**Comment by mcr** [comment]
The "ra" audit-request CoAP request is not necessary, and should not be shown in the example.

**Comment by csosto-pk** [comment]
> It seems convenient for some implementations to use CoAP from the Registrar to the MASA.

Some organization standing a COAP MASA on the Internet seems a far fetched scenario. I would not expect MASA to be sitting in a constrained environment. 

But again, I could be wrong and some may have appetite for a COAP MASA.

**Comment by mcr** [comment]
Consensus is that Registrar--> MASA will always be HTTPS.
The format of the voucher-request will match the format of the pledge->registrar voucher request.

**Comment by EskoDijk** [comment]
See comment in #52 of today for a possible rationale why CoAPS could be attractive on a constrained (cellular/LPWAN) uplink to MASA.  Then the reason why the MASA supports COAPS is not because it is itself constrained, but rather to offer support for constrained (e.g. cellular/IoT/LPWAN) uplinks of the Registrar towards the cloud.  Still, the real difference in terms of latency (roundtrips) and payload size (total) is still unclear.

**Comment by EskoDijk** [comment]
Note: if HTTPS is used for Registrar -> MASA communication , then also this communication will use the full (HTTP) URI paths to the EST/BRSKI functions and not the abbreviated (CoAP) URI paths. So the resource "/ra"  must be removed - as part of this ticket's work  - from the text since the Registrar will use "/requestauditlog" to MASA.  And the Pledge will not use this function towards Registrar if I'm correct.
