### ISSUE TITLE
with COSE signed CBOR, no standard for certificate chain

### ISSUE THREAD

**Issue by mcr** [anima-wg/constrained-voucher#59]
When COSE signed CBOR voucher, then there needs to be a way to include the chain of certificates from the Registrar to the MASA.

The https://www.ietf.org/archive/id/draft-ietf-cose-x509-07.html would seem to solve this problem for COSE.  Is this a better direction?

**Comment by mcr** [comment]
probably need to have x5bag

**Comment by EskoDijk** [comment]
the x5bag is more generic than the x5chain; using an x5bag the Registrar could include all the certs in the chain that was used for signing the COSE voucher request plus additional certificates like the "southbound TLS server certificate" that the Registrar used in its DTLS connection with the Pledge, and which is also indicated by the Pledge as the "proximity Registrar cert". 

The MASA could then verify two chains: 1) "proximity Registrar cert" that chains to the topmost Domain CA and 2) Registrar's signing cert that also chains to the same topmost Domain CA. 
(Note: doing such 2-chain verification instead of current 1-chain verification requires some text updates in BRSKI or a future RFC-update of BRSKI, as discussed.)

**Comment by mcr** [comment]
x5bag vs x5chain, and concluded we should use x5bag.
Bring up plan to COSE WG.

**Comment by siethower** [comment]
see also: https://tools.ietf.org/id/draft-schaad-cose-x509-03.html  x5bag/x5chain  
(was x5c in: previous: https://tools.ietf.org/id/draft-schaad-cose-x509-00.html)

**Comment by EskoDijk** [comment]
Our draft -12 now contains the x5bag solution; proposing to close this issue as solved.
