### ISSUE TITLE
can we use discovery over HTTP?

### ISSUE THREAD

**Issue by mcr** [anima-wg/constrained-voucher#61]
What is opinion of mnot to .well-known, whether to call only.

Whether to use /.well-known/brski.

/.well-known/core?rt=SOMETHING <- CoAP.

**Comment by mcr** [comment]
Can we discovery the presence of a /.well-known resource by some kind of operation on the /.well-known/FOO.
What happens if one GET /.well-known/something, can we expect a 404 vs 200 reply?

**Comment by mcr** [comment]
So how could one discovery "certificationauthority" for /.well-known/est/certificationauthority/simpleenroll ?

**Comment by pritikin** [comment]
I’m thinking the key of discovery is to determine the service is intended to be available. This needs to work even before trying to authenticate and should be able to be queried w/o doing a lot of work first. 

If you already know the FQDN then defining an HTTP landing page that always gives back 200 works to indicate if the service itself is available. Since the FQDN wasn't known our prior discussions were about DNS-SD or GRASP. At which point you don’t need an additional HTTP query.

- max

**Comment by EskoDijk** [comment]
In constrained BRSKI, what's the use case of calling "/.well-known/est/certificationauthority/simpleenroll" during the EST procedure?   There are some reasons not to include the "certificationauthority" part:
Firstly, because the Pledge is bootstrapping it doesn't know in advance the value of "certificationauthority" that it should use. Secondly, if it would use "/.well-known/est/simpleenroll" that would also work. RFC 7030 states on this "The EST server MUST provide services regardless of whether the additional path segment is present." . 

Of course once the BRSKI bootstrap is completed and the former Pledge (now EST-client) has its operational cert (LDevID), it could do further EST operations using the  extended "/.well-known/est/certificationauthority/<operation>"  path.  However, this poses a new question: what value of "certificationauthority" would the EST-client use then?  There's no standardized or pre-agreed format for the value of this string.  The EST-client does have the certificate of its own LDevID CA of course, with all information in it (Subject name, public key, etc) but there's no standard telling it how to translate all that into a string that the EST server will also understand.

**Comment by EskoDijk** [comment]
Adding to prior discussion: if a certain .well-known resource is not supported by the server a 404 would be returned. If there's a need for the client to "discover" / test if a certain well-known resource is supported prior to actually using it (e.g. via POST) there's no universally defined way to find this out.  A particular document that defines a resource - like /.well-known/brski - can define that a GET on this root resource will return a 200 OK if the functionality is supported i.e. root resource is present.

**Comment by petervanderstok** [comment]
Hi Esko,

I thought that the resource is present per definition when it is
returned by a /.well-known/core GET.

Peter
Esko Dijk schreef op 2020-12-01 10:06:

> Adding to prior discussion: if a certain .well-known resource is not supported by the server a 404 would be returned. If there's a need for the client to "discover" / test if a certain well-known resource is supported prior to actually using it (e.g. via POST) there's no universally defined way to find this out. A particular document that defines a resource - like /.well-known/brski - can define that a GET on this root resource will return a 200 OK if the functionality is supported i.e. root resource is present. 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/anima-wg/constrained-voucher/issues/61#issuecomment-736328794
[2]

**Comment by EskoDijk** [comment]
Oops, I'm not sure if my comment was useful given the context of HTTP. In constrained BRSKI, the Pledge is using CoAP not HTTP. So the current issue about discovery of resources over HTTP might be related instead to Registrar -> MASA communication.

@mcr was this intended by the current issue?

@petervanderstok Agree that if a resource was discovered over /.well-known/core the client can assume it is there - no further checks needed.  The issue raised was that when using HTTP, there's no such thing as GET /.well-known/core to see what resources are supported by the HTTP server. And an additional issue for both CoAP and HTTP is that any well-known resources that may exist such as /.well-known/brski or /.well-known/est are typically not returned in a CoAP discovery operation!!   See for example ace-coap-est-18 section 5.1, discovery example - the resources /.well-known/est/sen , sren, crts and all the others are not returned in the discovery response. Reason: because they're well-known. I.e. known to be there, intentionally placed under the .well-known space which is intended for accessing CoAP/HTTP resources without discoving them first.

**Comment by mcr** [comment]
Issues:

1. Do we need to discover onboarding systems other than BRSKI, at the level of the Registrar?

2. Do we need to discover EST vs CMP within a BRSKI system?

3. Do we need to signal which CA a pledge wants to enroll into at the EST/CMP level?  What if multiple certificates are needed (such as Thread vs BACnet).
The certificate request could signal this via a TBD attribute.

The proposed for the Thread/BACNet is that one first does an onboarding to the network, getting an LDevID, and then if another certificate is needed, then it does a second /simpleenroll with a CSR that distinguishes the need for to enroll into a second CA.

**Comment by mcr** [comment]
> 1. Do we need to discover onboarding systems other than BRSKI, at the level of the Registrar?

We think that this is handled by having multiple announcements from different join proxy, so the edge of the network has the information to connect to different systems (CHIP vs BRSKI vs EAP-NOOB vs BRSKI-TEAP, ...)

**Comment by mcr** [comment]
> 2. Do we need to discover EST vs CMP within a BRSKI system?

For instance, would we also want to return the existence of an attestation end-point?

**Comment by mcr** [comment]
We need a discussion draft on IoT architecture/configuration options.

**Comment by csosto-pk** [comment]
> > 1. Do we need to discover EST vs CMP within a BRSKI system?
> 
> For instance, would we also want to return the existence of an attestation end-point?
> Proposal: write a document that defines what happens when one does GET /.well-known/brski (?rt=???)
> 
> [The RD document, draft-ietf-core-resource-directory-26 says HTTP can be used for RD in section 4]

Sorry, seeing this late. I don't think we need the necessary complexity. draft-ietf-anima-bootstrapping-keyinfra assumes EST. I don't think constrained voucher needs to consider CMP.

**Comment by csosto-pk** [comment]
> 3\. Do we need to signal which CA a pledge wants to enroll into at the EST/CMP level?  What if multiple certificates are needed (such as Thread vs BACnet).
>     The certificate request could signal this via a TBD attribute.

Sorry, looking at this late. 

The way we were dealing with that was TLS SNI to route between different services, CAs etc. Other ways other than reaching different destinations are HTTP/1.x Host and HTTP/2 ":authority" pseudo-header.
