### ISSUE TITLE
can the pledge take the CA certificate from the certificate that is pinned?

### ISSUE THREAD

**Issue by mcr** [anima-wg/constrained-voucher#74]
When the pledge receives a voucher that pins the Registrar's CA, the pledge could avoid another round trip to do /est/crts, with the subsequent list of artifacts being transferred.

Is this a local decision on the pledge?
Is this something that the Registrar should communicate?
Is this something that the MASA can indicate in the voucher?

Should the Registrar be able to indicate to the Pledge that the thing pinned is not in fact a trust anchor, and that the pledge needs to get /crts?
Do we need a new attribute in the voucher-request (to be copied to the voucher by the MASA) to indicate what is permitted?

Choice:
1. leave things as they are, clarify that /crts is always required.
2. allow Registrar to indicate that the pinned certificate is acceptable as a trust anchor (default to 1).
3. allow Registrar to indicate that the pinned certificate is not acceptable as a trust anchor (default to not doing 1). [probably a incompatible change]

**Comment by EskoDijk** [comment]
There is one particular case where the Pledge can locally decide that the CA-cert in the Voucher can be trusted, and needs to go into its trust store: this is the case where the Pledge after getting the Voucher fetches its LDevID (e.g. /est/sen) and determines that this LDevID is signed by the same CA-cert - the one it got in the Voucher. You should always be able to trust your own identities' CA, right :-) 

The only thing that the Pledge doesn't know in this case is whether there are more CA certificates to be installed or not, to be obtained with a /est/crts request. (That was the separate discussion we had yesterday on using cryptographic hash to check which of the /est/crts certs the Pledge still needs to get.)

But: in the constrained implementation I'm working with we would like to have the Pledge store only one LDevID and one domain CA cert as the trust root, to save NVM use. In such case doing the local Pledge decision can work well, because the Pledge cannot store more CA certs anyway. In this case the procedure for Pledge is as follows:
1) BRSKI - get Voucher
2) EST - get LDevID (e.g. via /est/sen)
3) check if Voucher contains a CA-cert and if this CA is the signer of its LDevID.
3a) if both "yes", then install the Voucher's CA cert in the trust store
3b) if one or more "no" then: request GET /est/crts with Accept Option set to application/pkix-cert (i.e. a single cert) and install the resulting cert in the trust store

In the above scenario it would even be acceptable to remove the 'branch' code in step 3 and always get the (single) CA cert as it would simplify testing. I would not prefer to make constrained-BRSKI more complex by adding some signaling by the Registrar on whether the pinned cert needs to go into the trust store or not. 

The main driver for constrained Pledges bootstrap in this case is reducing code size&effort (e.g. no PKCS#7, no Blockwise); reducing NVM memory use (e.g. only single CA cert); reducing testing complexity; and reducing bandwidth only comes after that.

So my view is Choice 1 with the /crts being a SHOULD level requirement like in BRSKi. One valid exception case where /crts MAY be skipped is when the Pledge can hold only 1 CA cert and it already validated that its own LDevID has the pinned-domain-cert as a "parent" (signer), so that it knows 100% sure that this is the current/valid CA cert for its operational domain.

**Comment by EskoDijk** [comment]
PS the overall model proposed by my above comment is still the same as in BRSKI: the pinned-domain-cert is considered only a temporary trusted entity for the duration of the BRSKI bootstrap. Any different EST-defined trust anchors (CAs) will supersede the pinned domain cert.

However if the pinned-domain-cert happens to be identical to one of such trust anchors it is kept of course.
And if the the pinned-domain-cert happens to be the authority of (i.e. signer of) one of such trust anchors it MAY be kept as an additional trust anchor for as long as that EST-obtained trust anchor exists.   This works under the principle of "always trust the authority of your own LDevID's trust anchor" .

**Comment by csosto-pk** [comment]
+1 on option 1. SHOULD or RECOMMEND is fine by me.
