### ISSUE TITLE
obsolete the use of PKCS#7 in favour of pkix-cert format

### ISSUE THREAD

**Issue by mcr** [anima-wg/constrained-voucher#75]
As explained in #72, change the response to /crts from pkcs7 format, and instead mandate that pkix-cert format to be used.

**Comment by EskoDijk** [comment]
I would still like to keep supporting the existing EST-coaps "/crts" resource with content-format "application/pkix-cert" exactly as currently defined in EST-coaps. So this can be used to obtain 1 and exactly 1 CA-cert for the domain.
What would be useful for constrained-voucher is to clarify *which* 1 CA cert is returned by this in case the domain supports multiple.  In my view this 1 CA cert should be this one as also explained in #72:  the authority of the LDevID of the client. In other words, the CA that directly signs LDevID certificates produced by this EST server for the presently connected Pledge. Multiple CAs are not supported in this case; if the Registrar really needs multiple CAs then it will simply not implement "/crts" with the given content-format "application/pkix-cert" and return e.g. 4.06 Not Acceptable. 

This is useful for constrained devices that support storing only 1 Domain CA cert and that do not have the code for parsing PKCS#7 nor block-wise transfer. Using some crypto-hash based identification of CA certs like suggested in #72 comments isn't going to do much good in such use cases; it adds more round-trips and complexity.

**Comment by mcr** [comment]
I agree with your plan: return 1 important CA anchor.  
I don't think 4.06 is the right return, but we can argue about that in the document.
Be able to get two CAs is important when there is a roll of that intermediate CA key.

**Comment by csosto-pk** [comment]
> [...] the authority of the LDevID of the client. In other words, the CA that directly signs LDevID certificates produced by this EST server for the presently connected Pledge. 

That assumes the same CA signs the certs of the pledge's peers, right? Wouldn't it better to say that instead of the CA that signs the pledge's LDevID to avoid inadvertent confusion?

**Comment by EskoDijk** [comment]
@csosto-pk Yes indeed the same CA that signs the certs of the Pledge's peers. We could say that, thanks.

@mcr the 4.06 code is a CoAP standard way to signal that the requested content-format is not supported. And since the draft states "Servers MAY also support Content-Format TBD287" it implies that a server may not support it. In this case the server must respond 4.06 when the client asks for TBD287, there's no other nor better way as I can see.

@mcr Agree for the server it is mandatory to offer content-format 281 (PKCS#7) with multiple CA certs, e.g. in the case of key roll of the intermediate CA.  Clients requesting format 281 can then always get all relevant CAs.  However there may be constrained clients that only get *one* CA cert, in format TBD287. In case of a key roll of intermediate CA (iCA) these clients already store the "old" iCA with their LDevID and when they are triggered to do EST re-enroll (/sren) they will get their new LDevID under a new iCA, and will also ask for /crts again if the device sees that the LDevID is signed by a different iCA. In the /crts request with Accept:TBD287 they then get a single CA cert which is the new iCA.  

It would not be so useful to allow a single-cert format application/pkix-cert when the constrained client later on has to do the multi-cert PKCS#7 format anyway. The whole purpose of the single-cert format was to be able to get rid of the PKCS#7 code and 
 the block-wise CoAP code. But maybe I'm missing something here!
