### ISSUE TITLE
can we simplify the CSRattributes structure in EST?

### ISSUE THREAD

**Issue by mcr** [anima-wg/constrained-voucher#76]
can/should this be replaced by CBOR?

**Comment by EskoDijk** [comment]
The best simplification for constrained devices is to say that such devices MAY skip the csrattrs (/att) request alltogether. Instead they would construct a default CSR that includes following elements:
* Subject Distinguished Name fields exactly as copied from its IDevID , MANDATORY
* Any other fields the Pledge vendor has configured to be in the CSR, OPTIONAL

The EST server may still add additional information fields or even modify Subject DN fields prior to signing the LDevID so I don't see any issue in skipping this step. This can also be easily achieved without having to formally update the EST-coaps RFC because the server support of /att is already OPTIONAL so one can do without it so the client doesn't have to ask it.

A second-best simplifications would be to return a small CBOR structure that selects a profile from a limited number of supported profiles. E.g. have some flags about whether (Yes/no) to include a certain field that is common in the CSR.  For example include the organizationName DN component, yes or no. I think we still need better examples here of what should be configurable in this case.

And third? What I would not want to attempt is to use the same structure as the current ASN.1 encoded CSR-attributes but then transcribed to CBOR - that wouldn't reduce any of the complexity.

**Comment by csosto-pk** [comment]
EST-coaps made /att optional, so yes it is a may.

> Subject Distinguished Name fields exactly as copied from its IDevID 

We have some usecases here where that would not work. We want to pick our onw Subject-Name. 

All the time I have spent on EST, EST-coaps etc I have not seen a single CA or pledge or client implement or use CSRattributes. No one cares about it. The CAs have a profile and they issue certs based on that. They don't tell the client what to ask. 

I think we ought to not spend too much time on this doing CBOR etc. No one will iimplenent CSRattributes I am sure.

**Comment by EskoDijk** [comment]
@csosto-pk Agree, if the Pledge knows what to fill in in the Subject DN fields of the CSR then it can fill that in.  The use case I'm dealing with is a Pledge that has no clue what its identity in the domain is going to be (being new to it) so it will just fill in the default values it knows - the ones from its IDevID.  But there's more possible here, the MASA could e.g. indicate in the Voucher what these parameters should be in a vendor-specific way based on knowledge the MASA has of the customer site.

So we could mention the Pledge decides this and if it has no information to base itself on, it uses the IDevID Subject DN values?
