### ISSUE TITLE
explain PKIX-minimal behaviours of pledge

### ISSUE THREAD

**Issue by mcr** [anima-wg/constrained-voucher#91]
What is the minimum level of PKIX processing a Pledge can do?

**Comment by EskoDijk** [comment]
A good thought exercise is to assume a Pledge that cannot do PKIX chaining operations, and then goes through the entire bootstrap process and EST.  This is possible if
* Pledge can extract RPK of Registrar from Registrar's cert chain sent during DTLS handshake, even though it doesn't know how to validate this chain.
* Pledge uses RPK of Registrar for "proximity registrar" in its Voucher Request
* MASA pins RPK of Registrar only.
* Pledge does not verify its new LDevID against the domain CA certificate   (simply assumes it's ok as Registrar is trusted)

Now the Pledge is enrolled in the domain but it cannot trust anyone to communicate with (e.g. DTLS) based solely on Domain CA membership, because it cannot do chaining operations.  But it can be configured by a Commissioning Tool with some fixed identities of peers to talk to (e.g. RPK based) and trust.

So this seems the bare minimum.  A next step up to a higher level of processing, is to assume the Pledge can do PKIX chaining operations. Then we get e.g.:

* to perform the initial DTLS handshake to Registrar, the Pledge needs to be able to verify the Registrar's cert chain that is sent in the Certificate message. We can write that e.g. the Pledge MUST be able to handle at least 3 certificates in this chain:
   * Registrar RA cert
   * subordinate CA cert (optional)
   * domain CA cert  (MAY be root, or non-root)
* The implication for the Domain Registrar is that it SHOULD NOT use more than 3 certificates in this chain. Preferably it SHOULD use 2 in order to minimize data traffic on the constrained network.  Important is that this holds also when the domain CA cert is non-root; the Pledge simply can't handle the burden of even more certs.
* To later verify the Registrar against the pinned identity in the Voucher, the Pledge MUST be able to do the chaining operations to verify a chain e.g. Registrar <- subCA <- pinned-domainCA  or Registrar <- pinned-subCA .

**Comment by csosto-pk** [comment]
I am not sure we need normative language for how many certs the pledge should be able to parse. I see this example as a good example for how it would work with RPK and constrained pledges. That can go in an Appendix or something. But I am afraid that adding normative language about how many PKIX chain operations a pledge can do we are adding unnecessary complexity. 

BTW, I see the RPK case a really rare one and I doubt such a pledge can really be considered as doing EST-coaps workflows.

**Comment by EskoDijk** [comment]
@csosto-pk Seems like a good idea to have an Appendix with some of these deployment examples. There could be a "minimal" example in there that suggests a minimal configuration a Pledge has to support, without needing normative language in the main text.

The above RPK case where a Pledge cannot do PKIX chaining operations may be too "minimal" indeed. But to my surprise the Pledge can still correctly enroll in this case with some corner-cutting :)  It is almost / almost-not doing the EST-coaps workflow. We could bring up this example in the weekly call and decide if acceptable, or not.

**Comment by EskoDijk** [comment]
Update on my Feb 12 comment of the "minimal Pledge" that cannot do PKIX chaining operations;  there is a specific limitation when triggering a re-enroll of that Pledge:  in case the Registrar identity has changed or it does the re-enroll with another Registrar of the same Domain, then the Pledge is not able to verify the identity of that new/other Registrar against its Trust Anchor (CA). Because it cannot do chaining operations. So the "minimal Pledge" example seems to break proper EST making re-enrolls impossible.

**Comment by csosto-pk** [comment]
> So the "minimal Pledge" example seems to break proper EST making re-enrolls impossible.

Hmm, good point. If the Registrar changed it would need to go through bootstrapping again. 
But in the most common case where the Registrar is the same it would still work.

**Comment by EskoDijk** [comment]
Actually doing a factory reset or other way to trigger the bootstrap (BRSKI) again is a solution for this case. So it seems we can support the "minimal Pledge" albeit with some limitations w.r.t. regular BRSKI-EST. Now we have to decide whether we would like to have this minimal-Pledge in an Appendix (together with explaining the limitations), or not?

I could add this as an Appendix and we might always later decide to remove it again if the WG feels that the properties of EST / cert-based authentication are violated too much.

**Comment by csosto-pk** [comment]
> I could add this as an Appendix and we might always later decide to remove it again if the WG feels that the properties of EST / cert-based authentication are violated too much.

I always find Appendices can include useful information without cluttering the actual body of the standard. So, I like that idea.

**Comment by mcr** [comment]
> So this seems the bare minimum. A next step up to a higher level of processing, is to assume the Pledge can do PKIX chaining operations. Then we get e.g.:

I'd like to add some terminology to these levels of operation.

**Comment by mcr** [comment]
Could be an implementation document in lwig.

**Comment by EskoDijk** [comment]
The PR for #103 is now created with an Appendix: https://github.com/anima-wg/constrained-voucher/pull/196 . It does define now the minimal Pledge that cannot do EST re-enrollment, only re-bootstrap is possible.  There aren't much details about use of RPK when & where and cert-parsing / cert-chaining yes or no. That could be left to an lwig document or so.

After review of the PR we can likely close this issue and maybe create a new 'future' issue to define details of the minimal Pledge in some other document.

**Comment by EskoDijk** [comment]
PR #196 has been merged, closing this issue
